version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "gomod"
    directory: "/build"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "gomod"
    directory: "/website"
    schedule:
      interval: "daily"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "daily"
    target-branch: "develop"
